id: P008070
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22071
  title: རི་ནུབ།
  author: ''
  volumes:
    5fe67a4942514ca697a0cbce53128887:
      image_group_id: I1KG18061
      title: Volume 1 of ri nub/
      volume_number: 1
      total_pages: 186
      base_file: v001.txt
