id: P008070
initial_creation_type: ocr
source_metadata:
  id: bdr:W22071
  title: རི་ནུབ།
  author: ''
  volumes:
    8fef4ee2371b4fffbcbefe8665c8624b:
      image_group_id: I1KG18061
      title: ''
      volume_number: 1
      total_pages: 186
ebook_metadata:
  title: རི་ནུབ།
  author: ''
  sku: P008070
  cover: cover.jpg
  layers:
  - pagination
